"use client"
import { Metadata } from 'next'
import './globals.css'
// import { Inter } from 'next/font/google'
import { Provider } from 'react-redux';
import { store } from '@/store';
import { Footer } from '@/common/components/footer/footer.component';
import { BurgerMenu } from '@/common/components/burgerMenu/header.component';

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Provider store={store}>
          <BurgerMenu />
          {children}
          <Footer />
        </Provider>        
      </body>
    </html>
  )
}
